/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpro;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JPanel;

/**
 *
 * @author athiralekshmicv
 */
public class Initial extends javax.swing.JFrame   {
  public Object JFrame;


    
   
    public Initial() {
         
        
       
        super.setSize(50, 50);
        setSize(50,50);//To change body of generated methods, choose Tools | Templates.
    
        initComponents();
       
    }
  

   //Initial(JPanel jPanel1) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.text);

        jPanel1.setBackground(java.awt.SystemColor.text);
        jPanel1.setForeground(java.awt.SystemColor.text);
        jPanel1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jButton1.setBackground(java.awt.SystemColor.activeCaptionText);
        jButton1.setFont(new java.awt.Font("URW Bookman L", 0, 14)); // NOI18N
        jButton1.setForeground(java.awt.SystemColor.text);
        jButton1.setText("REGISTER");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(java.awt.SystemColor.info);
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/athiralekshmicv/perycyclic/books.jpeg")); // NOI18N
        jLabel1.setText("CENTRAL LIBRARY");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 250));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 250));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 230));

        jButton2.setBackground(java.awt.SystemColor.activeCaptionText);
        jButton2.setFont(new java.awt.Font("URW Bookman L", 0, 14)); // NOI18N
        jButton2.setForeground(java.awt.SystemColor.text);
        jButton2.setText("ISSUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.SystemColor.activeCaptionText);
        jButton3.setFont(new java.awt.Font("URW Bookman L", 0, 14)); // NOI18N
        jButton3.setForeground(java.awt.SystemColor.text);
        jButton3.setText("RETURN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.SystemColor.activeCaptionText);
        jButton5.setFont(new java.awt.Font("URW Bookman L", 0, 14)); // NOI18N
        jButton5.setForeground(java.awt.SystemColor.text);
        jButton5.setText("UPDATE PROFILE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(java.awt.SystemColor.activeCaptionText);
        jButton6.setFont(new java.awt.Font("URW Bookman L", 0, 14)); // NOI18N
        jButton6.setForeground(java.awt.SystemColor.text);
        jButton6.setText("CLOSE ACCOUNT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(java.awt.SystemColor.text);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("URW Chancery L", 0, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Central library established in 1995, by Mata Amritanandamayi\nDevi houses a large collection of literary works. Spanning over\nnumerous  categories, Central Library hosts over 10000 books \nincluding classics by veterans. ");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(718, 718, 718))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                
                Final np = new Final( jPanel1);
               
		 jPanel1.removeAll();
		
                jPanel1.setLayout(new BorderLayout());
		jPanel1.add( np,BorderLayout.CENTER);
                
                jPanel1.repaint();
		jPanel1.revalidate();
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                Issue np=new Issue(jPanel1);
                jPanel1.removeAll();
                jPanel1.setLayout(new BorderLayout());
                jPanel1.add(np,BorderLayout.SOUTH);
                jPanel1.repaint();
                jPanel1.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                Return np=new Return(jPanel1);
                jPanel1.removeAll();
                jPanel1.setLayout(new BorderLayout());
                jPanel1.add(np,BorderLayout.SOUTH);
                jPanel1.repaint();
                jPanel1.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                Update np=new Update(jPanel1);
                jPanel1.removeAll();
                jPanel1.setLayout(new BorderLayout());
                jPanel1.add(np,BorderLayout.SOUTH);
                jPanel1.repaint();
                jPanel1.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                
       
                Close_acc np=new Close_acc(jPanel1);
               // jPanel1.removeAll();
                
                jPanel1.setLayout(new BorderLayout());
                jPanel1.add(np,BorderLayout.SOUTH);
                jPanel1.repaint();
                jPanel1.revalidate();
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton6ActionPerformed
/*
    /**
     * @param args the command line arguments
     */
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
       /* Connection conn=null;
        Statement stmt=null;
        try{
           Class.forName("org.postgresql.Driver");
          conn =  DriverManager.getConnection("jdbc:postgresql://saktimayi:5432/examuser55", "examuser55", "examuser55");
          

        
        }
        catch(Exception e){
            System.out.println("Connection failed");
            
        }*/
        
         
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   
    /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* Connection conn=null;
        Statement stmt=null;
        try{
           Class.forName("org.postgresql.Driver");
          conn =  DriverManager.getConnection("jdbc:postgresql://saktimayi:5432/examuser55", "examuser55", "examuser55");
          

        
        }
        catch(Exception e){
            System.out.println("Connection failed");
            
        }*/
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Initial().setVisible(true);
            }
        });
    }

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

                }
